"""
sitecustomize hook — Claude Code OAuth bypass for hermes-agent.
===============================================================

This file is installed into the hermes-agent venv's site-packages as
``sitecustomize.py`` by ``install.sh``.  It runs once at Python interpreter
startup (before any user code) and hooks both:

- ``agent.error_classifier`` so Anthropic thinking-replay 400s are classified
  as recoverable before ``agent.conversation_loop`` binds ``classify_api_error``.
- ``agent.anthropic_adapter`` so OAuth billing/tool-name bypass behavior is
  applied immediately after the adapter loads.

To disable: run ``uninstall.sh`` or delete the sitecustomize.py from the
venv's site-packages and restart hermes-gateway.

DO NOT EDIT THIS FILE IN THE VENV — it will be overwritten on next install.
Edit the source in the hermes-claude-auth repo instead.
"""
# hermes-claude-auth managed — do not remove this marker

from __future__ import annotations

import os
import sys

_PATCHES_DIR = os.environ.get(
    "HERMES_PATCHES_DIR",
    os.path.expanduser("~/.hermes/patches"),
)
_TARGET_MODULE = "agent.anthropic_adapter"  # Back-compat for tests/older callers.

if os.path.isdir(_PATCHES_DIR) and _PATCHES_DIR not in sys.path:
    sys.path.insert(0, _PATCHES_DIR)


def _make_import_hook(target_module, patcher_fn, label):
    try:
        from importlib.abc import MetaPathFinder
        from importlib.util import find_spec
    except ImportError:
        return

    class _ClaudeCodeBypassFinder(MetaPathFinder):
        _patched = False

        def find_spec(self, fullname, path=None, target=None):
            if fullname != target_module or self._patched:
                return None

            if self in sys.meta_path:
                sys.meta_path.remove(self)
            try:
                spec = find_spec(fullname)
            finally:
                if self not in sys.meta_path:
                    sys.meta_path.insert(0, self)

            if spec is None or spec.loader is None:
                return None

            original_exec = getattr(spec.loader, "exec_module", None)
            if not callable(original_exec):
                return None

            finder = self

            def patched_exec(module):
                original_exec(module)
                finder._patched = True
                try:
                    patcher_fn(module)
                except Exception as exc:
                    import traceback

                    sys.stderr.write(
                        f"[{label}] bypass failed: {type(exc).__name__}: {exc}\n"
                    )
                    traceback.print_exc(file=sys.stderr)

            spec.loader.exec_module = patched_exec
            return spec

    sys.meta_path.insert(0, _ClaudeCodeBypassFinder())


def _load_billing_bypass():
    try:
        import anthropic_billing_bypass
    except ImportError:
        return None
    return anthropic_billing_bypass


def _patch_anthropic_adapter(module):
    anthropic_billing_bypass = _load_billing_bypass()
    if anthropic_billing_bypass is None:
        return

    ok = anthropic_billing_bypass.apply_patches(module)
    if not ok:
        sys.stderr.write(
            "[hermes-claude-auth] bypass declined "
            "(API incompatibility detected)\n"
        )


def _patch_error_classifier(_module):
    anthropic_billing_bypass = _load_billing_bypass()
    if anthropic_billing_bypass is None:
        return

    anthropic_billing_bypass._install_thinking_replay_classifier_patch()


def _patch_run_agent(module):
    """Install subscription rate-limit auto-wait on AIAgent.

    Triggered when run_agent is first imported (the gateway startup sequence
    imports it before the first API call).  Patches the two interruptible
    API-call methods so a Claude Pro/Max 5-hour-window 429 sleeps until the
    window resets and retries transparently, instead of letting Hermes core's
    120s-backoff-capped loop give up and surface "rate-limiting requests"
    to Telegram.
    """
    anthropic_billing_bypass = _load_billing_bypass()
    if anthropic_billing_bypass is None:
        return

    try:
        ok = anthropic_billing_bypass.install_rate_limit_autowait(module)
        if ok:
            sys.stderr.write("[hermes-claude-auth] rate-limit auto-wait installed\n")
    except Exception as exc:
        sys.stderr.write(
            f"[hermes-claude-auth] rate-limit auto-wait install failed: "
            f"{type(exc).__name__}: {exc}\n"
        )


def _install_hook() -> None:
    """Back-compatible helper: install only the historical adapter hook."""
    _make_import_hook(_TARGET_MODULE, _patch_anthropic_adapter, "hermes-claude-auth")


def _install_all_hooks() -> None:
    _make_import_hook(
        "agent.error_classifier",
        _patch_error_classifier,
        "hermes-claude-auth-errors",
    )
    _make_import_hook(
        "run_agent",
        _patch_run_agent,
        "hermes-claude-auth-rl-autowait",
    )
    _install_hook()


try:
    _install_all_hooks()
except Exception as _exc:
    sys.stderr.write(f"[hermes-claude-auth] hook install failed: {_exc}\n")
