"""
sitecustomize hook — Claude Code OAuth bypass for hermes-agent.
===============================================================

This file is installed into the hermes-agent venv's site-packages as
``sitecustomize.py`` by ``install.sh`` or ``install.ps1``.  It runs once
at Python interpreter startup (before any user code) and hooks the import of
``agent.anthropic_adapter`` so that the billing bypass patch is applied
immediately after the module loads.

To disable: run ``uninstall.sh`` or delete the sitecustomize.py from the
venv's site-packages and restart hermes-gateway.

DO NOT EDIT THIS FILE IN THE VENV — it will be overwritten on next install.
Edit the source in the hermes-claude-auth repo instead.
"""
# hermes-claude-auth managed — do not remove this marker

from __future__ import annotations

import os
import sys

def _candidate_hermes_homes() -> list[str]:
    """Return every plausible Hermes data dir, most specific first.

    ``HERMES_HOME`` may point at a *profile* directory
    (``...\\hermes\\profiles\\<name>``) rather than the install root.
    Patches are installed once at the root, so a profile-scoped
    HERMES_HOME must still fall back to the root — otherwise the
    bypass silently fails to import (ModuleNotFoundError).
    """
    homes: list[str] = []

    def _add(path: str | None) -> None:
        if path:
            p = os.path.abspath(os.path.expanduser(path))
            if p not in homes:
                homes.append(p)

    configured = os.environ.get("HERMES_HOME")
    _add(configured)

    # If HERMES_HOME is a profile dir, walk up past 'profiles/<name>'.
    if configured:
        p = os.path.abspath(os.path.expanduser(configured))
        parent = os.path.dirname(p)
        if os.path.basename(parent).lower() == "profiles":
            _add(os.path.dirname(parent))

    if os.name == "nt":
        local_app_data = os.environ.get("LOCALAPPDATA")
        if local_app_data:
            _add(os.path.join(local_app_data, "hermes"))
    _add("~/.hermes")
    return homes


def _default_hermes_home() -> str:
    """Backwards-compatible single-value resolver."""
    homes = _candidate_hermes_homes()
    return homes[0] if homes else os.path.expanduser("~/.hermes")


def _resolve_patches_dir() -> str:
    """Pick the first patches dir that actually contains the bypass module."""
    explicit = os.environ.get("HERMES_PATCHES_DIR")
    if explicit:
        return os.path.expanduser(explicit)

    fallback = None
    for home in _candidate_hermes_homes():
        cand = os.path.join(home, "patches")
        if fallback is None:
            fallback = cand
        if os.path.isfile(os.path.join(cand, "anthropic_billing_bypass.py")):
            return cand
    return fallback or os.path.join(_default_hermes_home(), "patches")


_PATCHES_DIR = _resolve_patches_dir()
_TARGET_MODULE = "agent.anthropic_adapter"

if os.path.isdir(_PATCHES_DIR) and _PATCHES_DIR not in sys.path:
    sys.path.insert(0, _PATCHES_DIR)


def _install_hook() -> None:
    try:
        from importlib.abc import MetaPathFinder
        from importlib.util import find_spec
    except ImportError:
        return

    class _ClaudeCodeBypassFinder(MetaPathFinder):
        _patched = False

        def find_spec(self, fullname, path=None, target=None):  # type: ignore[override]
            if fullname != _TARGET_MODULE or self._patched:
                return None

            # Temporarily remove ourselves to avoid recursion during find_spec.
            if self in sys.meta_path:
                sys.meta_path.remove(self)
            try:
                spec = find_spec(fullname)
            finally:
                if self not in sys.meta_path:
                    sys.meta_path.insert(0, self)

            if spec is None or spec.loader is None:
                return None

            original_exec = getattr(spec.loader, "exec_module", None)
            if not callable(original_exec):
                return None

            finder = self

            def patched_exec(module):  # type: ignore[no-untyped-def]
                original_exec(module)
                finder._patched = True
                try:
                    import anthropic_billing_bypass

                    anthropic_billing_bypass.apply_patches(module)
                except Exception as exc:
                    import traceback

                    sys.stderr.write(
                        f"[hermes-claude-auth] bypass failed: "
                        f"{type(exc).__name__}: {exc}\n"
                    )
                    traceback.print_exc(file=sys.stderr)

            spec.loader.exec_module = patched_exec  # type: ignore[attr-defined]
            return spec

    sys.meta_path.insert(0, _ClaudeCodeBypassFinder())


try:
    _install_hook()
except Exception as _exc:
    sys.stderr.write(f"[hermes-claude-auth] hook install failed: {_exc}\n")
