"""
sitecustomize hook — Claude Code OAuth bypass for hermes-agent.
===============================================================

This file is installed into the hermes-agent venv's site-packages as
``sitecustomize.py`` by ``install.sh``.  It runs once at Python interpreter
startup (before any user code) and hooks the import of
``agent.anthropic_adapter`` so that the billing bypass patch is applied
immediately after the module loads.

To disable: run ``uninstall.sh`` or delete the sitecustomize.py from the
venv's site-packages and restart hermes-gateway.

DO NOT EDIT THIS FILE IN THE VENV — it will be overwritten on next install.
Edit the source in the hermes-claude-auth repo instead.
"""
# hermes-claude-auth managed — do not remove this marker

from __future__ import annotations

import os
import sys

def _resolve_patches_dir() -> str:
    """Locate ``anthropic_billing_bypass.py`` across Hermes install layouts.

    Hermes supports multiple profiles under
    ``$HERMES_HOME/profiles/<name>/`` (e.g. ``default``, ``casa``,
    ``alldrivers-*``).  The billing bypass is installed **once** at the
    Hermes data root (``$HERMES_HOME/patches/``), not per profile, yet
    ``HERMES_HOME`` may legitimately point at a profile directory.  Resolve
    in this order, taking the first path that actually contains the patch:

      1. ``$HERMES_PATCHES_DIR``            (explicit override, wins outright)
      2. ``$HERMES_HOME``                  (when HERMES_HOME holds patches/)
      3. ``$HERMES_HOME/../..``            (when HERMES_HOME is a profile dir:
                                            ``.../profiles/<name>`` → data root)
      4. ``%LOCALAPPDATA%/hermes``         (Windows native default)
      5. ``~/.hermes``                     (POSIX default)

    Falls back to the legacy ``~/.hermes/patches`` if none match, so the
    behaviour is unchanged for single-profile installs.
    """
    explicit = os.environ.get("HERMES_PATCHES_DIR")
    if explicit:
        return explicit

    candidates = []
    home = os.environ.get("HERMES_HOME")
    if home:
        candidates.append(home)
        # HERMES_HOME = .../hermes/profiles/<name>  → data root is two levels up
        if os.path.basename(os.path.dirname(home)).lower() == "profiles":
            candidates.append(os.path.dirname(os.path.dirname(home)))
    localappdata = os.environ.get("LOCALAPPDATA")
    if localappdata:
        candidates.append(os.path.join(localappdata, "hermes"))
    candidates.append(os.path.expanduser("~/.hermes"))

    patch_name = "anthropic_billing_bypass.py"
    for cand in candidates:
        if not cand or not os.path.isdir(cand):
            continue
        if os.path.isfile(os.path.join(cand, "patches", patch_name)):
            return os.path.join(cand, "patches")
    # Fallback: legacy single-profile default.
    return os.path.expanduser("~/.hermes/patches")


_PATCHES_DIR = _resolve_patches_dir()
_TARGET_MODULE = "agent.anthropic_adapter"

if os.path.isdir(_PATCHES_DIR) and _PATCHES_DIR not in sys.path:
    sys.path.insert(0, _PATCHES_DIR)


def _install_hook() -> None:
    try:
        from importlib.abc import MetaPathFinder
        from importlib.util import find_spec
    except ImportError:
        return

    class _ClaudeCodeBypassFinder(MetaPathFinder):
        _patched = False

        def find_spec(self, fullname, path=None, target=None):  # type: ignore[override]
            if fullname != _TARGET_MODULE or self._patched:
                return None

            # Temporarily remove ourselves to avoid recursion during find_spec.
            if self in sys.meta_path:
                sys.meta_path.remove(self)
            try:
                spec = find_spec(fullname)
            finally:
                if self not in sys.meta_path:
                    sys.meta_path.insert(0, self)

            if spec is None or spec.loader is None:
                return None

            original_exec = getattr(spec.loader, "exec_module", None)
            if not callable(original_exec):
                return None

            finder = self

            def patched_exec(module):  # type: ignore[no-untyped-def]
                original_exec(module)
                finder._patched = True
                try:
                    import anthropic_billing_bypass

                    anthropic_billing_bypass.apply_patches(module)
                except Exception as exc:
                    import traceback

                    sys.stderr.write(
                        f"[hermes-claude-auth] bypass failed: "
                        f"{type(exc).__name__}: {exc}\n"
                    )
                    traceback.print_exc(file=sys.stderr)

            spec.loader.exec_module = patched_exec  # type: ignore[attr-defined]
            return spec

    sys.meta_path.insert(0, _ClaudeCodeBypassFinder())


try:
    _install_hook()
except Exception as _exc:
    sys.stderr.write(f"[hermes-claude-auth] hook install failed: {_exc}\n")
